//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCUniversity.Models.Db
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Registration
    {
        public int RegistrationID { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateLastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Qualification { get; set; }
        public Nullable<double> PerMarks { get; set; }
        public string CourseName { get; set; }
        public string pic { get; set; }
        public Nullable<System.DateTime> RowCreatedDate { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
